idf_component_register(
  SRCS "main.c"
    "../src/config.c"
    "../src/model.c"
    "../src/types.c"
    "../src/drivers/driver_display.c"
    "../src/drivers/driver_led.c"
    "../src/drivers/driver_sound.c"
    "../src/drivers/driver_storage.c"
    "../src/controllers/controller_central.c"
    "../src/controllers/controller_light.c"
    "../src/controllers/controller_sound.c"
    "../src/controllers/controller_storage.c"
    "../src/controllers/controller_ui.c"
    "../src/ui/ui.c"
    "../src/ui/layer/layer_top.c"
    "../src/ui/screen/screen_home.c"
    "../src/ui/screen/screen_light.c"
    "../src/ui/screen/screen_sound.c"
    "../src/ui/widget/color_picker.c"

  INCLUDE_DIRS "../src"
    "../src/drivers"
    "../src/controllers"
    "../src/ui"
    "../src/ui/layer"
    "../src/ui/screen"
    "../src/ui/widget"

  REQUIRES esp_lcd esp_timer esp_driver_sdmmc esp_driver_i2s fatfs
)
