#include "nav_button.h"

const lv_style_const_prop_t STYLE_NAV_BUTTON_props[] = {
    LV_STYLE_CONST_WIDTH(70), LV_STYLE_CONST_HEIGHT(70),
    LV_STYLE_CONST_RADIUS(LV_RADIUS_CIRCLE), LV_STYLE_CONST_BORDER_WIDTH(0),
    LV_STYLE_CONST_PROPS_END};

const lv_style_const_prop_t STYLE_NAV_BUTTON_ICON_props[] = {
    LV_STYLE_CONST_TEXT_FONT(&lv_font_montserrat_28),
    LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
    LV_STYLE_CONST_TEXT_COLOR(LV_COLOR_MAKE(0xFF, 0xFF, 0xFF)),
    LV_STYLE_CONST_PROPS_END};

LV_STYLE_CONST_INIT(STYLE_NAV_BUTTON, STYLE_NAV_BUTTON_props);
LV_STYLE_CONST_INIT(STYLE_NAV_BUTTON_ICON, STYLE_NAV_BUTTON_ICON_props);